name: matomo_tracker
description: A fully cross-platform wrap of the Matomo tracking client for
  Flutter, using the Matomo API.
version: 6.0.0-dev.1
homepage: https://github.com/Floating-Dartists/matomo-tracker
repository: https://github.com/Floating-Dartists/matomo-tracker
issue_tracker: https://github.com/Floating-Dartists/matomo-tracker/issues
topics:
  - matomo
  - analytics

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  device_info_plus: ^11.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  package_info_plus: ^8.0.3
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  custom_lint: ">=0.5.4 <0.8.0"
  fd_lints: ^2.3.0
  flutter_test:
    sdk: flutter
  meta: ^1.12.0
  mocktail: ^1.0.4
