name: matomo_tracker
description: A fully cross-platform wrap of the Matomo tracking client for
  Flutter, using the Matomo API.
version: 5.0.0-dev.1
homepage: https://github.com/Floating-Dartists/matomo-tracker
repository: https://github.com/Floating-Dartists/matomo-tracker
issue_tracker: https://github.com/Floating-Dartists/matomo-tracker/issues
topics:
  - matomo
  - analytics

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.17.2
  device_info_plus: ">=9.1.0 <11.0.0"
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_info_plus: ">=4.2.0 <7.0.0"
  shared_preferences: ^2.2.2
  uuid: ">=4.1.0 <6.0.0"

dev_dependencies:
  custom_lint: ^0.5.4
  fd_lints: ^2.2.0
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  mocktail: ^1.0.2

flutter: null
